# prometheus_grafana_docker.yml
# to start:
#          docker-compose -f prometheus_grafana_docker.yml up
#
version: '2'
services:
  prometheus:
    image: prom/prometheus
    volumes:
    command:
      - '-config.file=/prometheus/config.yml'
    ports:
      - '9090:9090'
  node-exporter:
    image: prom/node-exporter
    ports:
      - '9100:9100'
  pushgateway:
    image: prom/pushgateway
    ports:
      - '9091:9091'
  collectd-exporter:
    image: prom/collectd-exporter
    ports:
      - '9103:9103'
      - '25826:25826/udp'
    command:
      - '-collectd.listen-address=":25826"
  grafana:
    image: grafana/grafana
    environment:
         - GF_SECURITY_ADMIN_PASSWORD=pass
    volumes:
         - grafana_data:/var/lib/grafana
    depends_on:
         - prometheus
    ports:
         - '3000:3000'

volumes:
    prometheus_data: {}
    grafana_data: {}

