# prometheus_grafana_docker.yml
# to start:
#          docker-compose -f prometheus_grafana_docker.yml up
#
version: '2'
services:
  collectd:
    build: ./collectd
    depends_on:
      - node-exporter
      - prometheus
      - grafana
  prometheus:
    image: prom/prometheus
    depends_on:
      grafana
    volumes:
      - ./prometheus:/prometheus
    command:
      - '-config.file=/prometheus/config.yml'
      - '-storage.local.retention=168h'       #set default retention of metrics
    ports:
      - '9090:9090'
  node-exporter:
    image: prom/node-exporter
    depends_on:
      - prometheus
      - grafana
    ports:
      - '9100:9100'
  pushgateway:
    image: prom/pushgateway
    depends_on:
      - prometheus
      - grafana
    ports:
      - '9091:9091'
  collectd-exporter:
    image: prom/collectd-exporter
    depends_on:
      - prometheus
      - grafana
      - collectd
    ports:
      - '9103:9103'
      - '25826:25826/udp'
    command:
      - '-collectd.listen-address=":25826"
  grafana:
    image: grafana/grafana
    environment:
         - GF_SECURITY_ADMIN_PASSWORD=pass
    volumes:
         - ./grafana/data:/var/lib/grafana
         - ./grafana/etc:/etc/grafana
    ports:
         - '3000:3000'

volumes:
    prometheus_data: {}
    grafana_data: {}

